export * from './bars/DiscountBar.jsx'
export * from './bars/Footer.jsx'
export * from './bars/Header.jsx'
export * from './bars/SubscribeBar.jsx'
export * from './forProducts/Products.jsx'
export * from './forCategories/Categories.jsx'
export * from './forHomePage/AdsSlider.jsx'